### ISSUE TITLE
The end of the "WORKING-STORAGE SECTION" is not recognized correctly.

### ISSUE THREAD

**Issue by MrT201509** [mridoni/gixsql#160] opened 2023-07-22 07:18 UTC
Hello again.
Given is the following program code:

IDENTIFICATION DIVISION.
PROGRAM-ID. testwss.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 x PIC X(1) VALUE "x".
PROCEDURE DIVISION.
DISPLAY x.

Compiler reports build-error:

TEST_WSS.cbsql(16): error: 'x' cannot be used here

Adding a new line at the end of the "WORKING-STORAGE SECTION" (with or without a comment or a definition of another variable) solves the problem:

IDENTIFICATION DIVISION.
PROGRAM-ID. testwss.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 x PIC X(1) VALUE "x".

PROCEDURE DIVISION.
DISPLAY x.

This is very confusing!

**Comment by mridoni** [comment] 2023-07-25 12:27
I moved the issue here since it is actually a GixSQL issue

**Comment by MrT201509** [comment] 2023-07-25 13:04
Thank you for helping. I close the issue now.

**Comment by GitMensch** [comment] 2023-07-25 13:07
Please reopen - the issue is a severe problem in gixpp which isn't fixed.

**Comment by mridoni** [comment] 2023-09-17 11:11
Fixed by dd9050ec0464a993cd2a4bbf4aee431b06c0bfd8. BTW: the same problem happened in the LINKAGE section, it was also fixed there.

**Closed by mridoni** 2023-09-17 11:11 UTC
Labels: bug
